baseURL = 'https://holliejohnson.github.io/'
languageCode = 'en-us'
title = 'Hollie Johnson'

# Change the default theme to be use when building the site with Hugo
theme = "mini"

publishDir = "docs"
