baseURL: 'https://holliejohnson.github.io/'
languageCode: en-uk
title: Hollie Johnson

# Change the default theme to be use when building the site with Hugo
theme: PaperMod

#publishDir: docs

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  tag: tags
  category: categories

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Posts
                  url: posts/
                  weight: 5
                - name: Tags
                  url: tags/
                  weight: 10


params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: ""
  author: Hollie
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  #ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: false
  # comments: false
  images: ["papermod-cover.png"]

  profileMode:
        enabled: true
        title: Hi, I'm Hollie 🌻
        subtitle: " 
        **ml | stats | data science | development** \n\n

        possibly also bikes and benchpress \n
        
        and other things \n 

          \n

        📍 Newcastle, UK
        "

        imageUrl: "/img/hollie.jpg"
        imageTitle: my image
        imageWidth: 120
        imageHeight: 120
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags
            - name: HJ Strength Coaching
              url: "https://holliejohnson.github.io/hj_strengthcoaching"
            


  socialIcons:
        - name: github
          url: "https://github.com/holliejohnson"
        - name: linkedin
          url: "https://www.linkedin.com/in/hollie-johnson/"
