baseURL: 'https://holliejohnson.github.io/'
languageCode: en-uk
title: Hollie Johnson

# Change the default theme to be use when building the site with Hugo
theme: PaperMod

publishDir: docs

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  tag: tags
  category: categories

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Tags
                  url: tags/
                  weight: 10


params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "My site"
  author: Hollie
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  #ShowShareButtons: true
  #ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  # comments: false
  images: ["papermod-cover.png"]

  profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

  homeInfoParams:
      Title: Hi I'm Hollie from Newcastle
      Content: I'm writing about things I've learned, or are cool or interesting

  socialIcons:
        - name: twitter
          url: "https://twitter.com/holliealice_"
        - name: github
          url: "https://github.com/holliejohnson"
        - name: linkedin
          url: "https://www.linkedin.com/in/hollie-johnson/"
